[package]
name = "rgrab-tests"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
common = { path = "../crates/common" }
storage = { path = "../crates/storage" }
serde_json = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }
